import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '@/components/Header'; 
import Footer from '@/components/Footer'; 
import { AuthProvider } from '@/contexts/AuthContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  verification: {
    google: "fwAOYgQCy1Fc2EEaRZn_ziXtHdPAPh5M_Q6F-jBDoUY",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de">
      <head>
        <meta name="google-site-verification" content="fwAOYgQCy1Fc2EEaRZn_ziXtHdPAPh5M_Q6F-jBDoUY" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white flex flex-col min-h-screen`}
      >
        <AuthProvider>
          <Header />
          {/* Added px-4 for horizontal safety margin. Main area is still full-width for background purposes. */}
          <main className="flex-grow px-4 pt-20 pb-24">
            {children}
          </main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
